run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - gocyclo
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
    - gosimple

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
