# permissions for end users to view openapiaggregators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: golang
    app.kubernetes.io/managed-by: kustomize
  name: openapiaggregator-viewer-role
rules:
- apiGroups:
  - observability.aggregator.io
  resources:
  - openapiaggregators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.aggregator.io
  resources:
  - openapiaggregators/status
  verbs:
  - get
