---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - observability.aggregator.io
  resources:
  - openapiaggregators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.aggregator.io
  resources:
  - openapiaggregators/finalizers
  verbs:
  - update
- apiGroups:
  - observability.aggregator.io
  resources:
  - openapiaggregators/status
  verbs:
  - get
  - patch
  - update
