name: PR Check

on:
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.23'
  RUNNING_IN_CI: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Cache tools
      uses: actions/cache@v4
      with:
        path: |
          bin/
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-tools-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install tools
      run: |
        echo "::group::Installing development tools"
        make tools
        echo "::endgroup::"

    - name: Build and test
      run: |
        echo "::group::Building project"
        make build
        echo "::endgroup::"
        
        echo "::group::Running tests"
        make test
        echo "::endgroup::"
