name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: true

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Build
      run: make build

    - name: Run tests
      run: make test
