name: PR Check

on:
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.22'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Setup environment
      run: |
        mkdir -p bin
        chmod 755 bin

    - name: Run tests
      run: make test

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Setup build environment
      run: |
        mkdir -p bin
        chmod 755 bin
        echo "GOOS=linux" >> $GITHUB_ENV
        echo "CGO_ENABLED=0" >> $GITHUB_ENV
        echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV

    - name: Build binary
      run: |
        go mod download
        GOARCH=${{ matrix.arch }} make build
