name: PR Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Build
      run: |
        GOARCH=${{ matrix.arch }} make build
        
    - name: Run tests
      run: make test

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: manager-${{ matrix.arch }}
        path: bin/manager-${{ matrix.arch }}
